### ISSUE TITLE
[Arabic display] bad display of Job Title in Arabic language

### ISSUE THREAD

**Issue by wassimmhamdi** [Meeds-io/meeds#157] opened 2022-05-20 13:29 UTC
**Describe the bug**
when you hover on a user in the stream for example , a poup-over contain some information appear with bad display of the job title for this user

**To Reproduce**
1. Go to builders.meeds.io
2. change the language to Arab
3. Go to stream
4. Hover on the user
5. See that the job title have a bad display

**Expected behavior**
the job title must have a good display

**Screenshots**
![elipsis-ar](https://user-images.githubusercontent.com/92787714/169538354-0cbabc3f-b9e6-430e-9cf7-6742271e10e3.png)

**Comment by srenault-meeds** [comment] 2022-11-24 10:07
I am not arabic speaker but as the position is in English, isn't that normal display?
@Imenmakni can you confirm please?

**Comment by srenault-meeds** [comment] 2023-11-02 12:07
Hello @boubaker can you please help me understand what the problem is here?
Thanks

**Comment by boubaker** [comment] 2023-11-02 15:05
I think you can close it since it has changed. The display should be ok by now.

**Closed as completed** 2023-11-02 15:22 UTC
