### ISSUE TITLE
History of transactions in wallet not displayed 

### ISSUE THREAD

**Issue by wassimmhamdi** [Meeds-io/meeds#153] opened 2022-05-20 10:41 UTC
**Describe the bug**
in the wallet, when we click on the button Last transaction no history of transactions display   

**To Reproduce**
1. Go to builders.meeds.io
2. Go to your Wallet
3. Click on the button Last transaction
4. See that in drawer there is the message  _No recent transactions_

**Expected behavior**
all the transaction must bee display and the user can see his/her transaction 

**Screenshots**
![lastTransaction](https://user-images.githubusercontent.com/92787714/169511307-c1d4bf83-1cae-46c1-9953-103f3152d704.png)

**Comment by plamarque** [comment] 2022-05-20 22:30
the meeds wallet app can only display transactions it has done itself. Just like Metamask, it won't show you transactions done with other apps. Is it the wallet you initialized from builders ? or restored from private key? or maybe connected through metamask?

**Comment by srenault-meeds** [comment] 2022-11-24 11:02
As we don't receive replies from you @wassimmhamdi and as I can't reproduce it, let me close this issue. I will reopen it as soon as you reply to us.

**Closed as completed** 2022-11-24 11:02 UTC
