### ISSUE TITLE
[bug] [ANALYTICS] space host have access to action menu of analytics page

### ISSUE THREAD

**Issue by mkrout** [Meeds-io/meeds#2585] opened 2024-11-15 14:37 UTC
**Rationale**
An analytics portlet (rate, table, chart) can be integrated into a space page to allow space animators or members to consult data on activities in the space.

Analytics provide very precise information on user usage. It is essential to be able to limit the use of these analytics by blocking the possibility of edit settings and view samples of the portlets

** requirements**

As a user with  space permissions : "Edit navigation"
Then the user can edit the portlet, json and view samples (all the options in the 3 dots)

As a user without space permission : "Edit navigation"
Than the user cannot edit the portlet, json and view samples (all the options in the 3 dots)

![image](https://github.com/user-attachments/assets/7f4e59e0-7f45-4a7e-b03f-726be492ae5a)

**Comment by boubaker** [comment] 2024-11-18 13:35
Not a bug, since this is an expected behavior, thus requalified to Feature enhancement project instead. Thanks for your understanding.

**Comment by margondicco** [comment] 2024-11-18 14:07
Hello, @Jihed525 , after discussion with Meeds lab, it wasn't an issue. So we should do a roll back. 

I wrote the new requirement here

cc @mkrout @srenault-meeds 

Thank you

**Comment by srenault-meeds** [comment] 2024-11-18 14:38
If I may, here is a more detailed expectation:

> Platform admins, Space Coordinator (AKA SuperManager) can edit navigation and thus, these users can access analytics settings: view samples, edit settings, edit json settings

> If for  **permission: "Edit navigation"**,
Space admins or Group members are identified in space template configuration, OR in space permissions as allowed to use such permission
Then , they can access analytics settings (view samples, portlet edition, json edition) if they can edit navigation as well

> If no specification for navigation permission in space template OR space permission, then space admins cannot access analytics settings

**Comment by mkrout** [comment] 2024-11-18 14:47
> Hello, @Jihed525 , after discussion with Meeds lab, it wasn't an issue. So we should do a roll back.
> 
> I wrote the new requirement here
> 
> cc @mkrout @srenault-meeds
> 
> Thank you

Reverted

**Comment by boubaker** [comment] 2024-12-25 17:55
Fixed by https://github.com/Meeds-io/analytics/pull/257

**Closed as completed by boubaker** 2024-12-25 17:55 UTC
Labels: Analytics
